###############################################################################
# Database configuration

# Connection string is in Go pq driver format:
# host=<host> port=<port> user=<databaseUser> password=<databaseUserPassword> dbname=<databaseName>

[database]

connection_string = "host=localhost port=5432 user=postgres password=admin123 dbname=courseonline sslmode=disable"
max_idle_connections = 5
max_open_connections = 10
connection_max_lifetime = "60s"
driver_name = "postgres"
###############################################################################
# HTTP server configuration

[http]
host = "localhost"
server_address = ":8888"
###############################################################################
# jwt server configuration

[jwt]

api_secret="mysecret"
token_hour_lifespan="24h"
###############################################################################
