// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateCart(ctx context.Context, arg CreateCartParams) (*Cart, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (*Course, error)
	CreateOrderCourse(ctx context.Context, arg CreateOrderCourseParams) (*OrderCourse, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteCart(ctx context.Context, cartID int32) error
	DeleteCourse(ctx context.Context, coursID int32) error
	DeleteOrderCourse(ctx context.Context, uscoID int32) error
	DeleteUser(ctx context.Context, userID int32) error
	GetAllCarts(ctx context.Context) ([]*Cart, error)
	GetAllCourses(ctx context.Context) ([]*Course, error)
	GetAllOrderCourses(ctx context.Context) ([]*OrderCourse, error)
	GetAllUsers(ctx context.Context) ([]*User, error)
	GetCartByID(ctx context.Context, cartID int32) (*Cart, error)
	GetCourseByID(ctx context.Context, coursID int32) (*Course, error)
	GetOrderCourseByID(ctx context.Context, uscoID int32) (*OrderCourse, error)
	GetUserByID(ctx context.Context, userID int32) (*User, error)
	UpdateCart(ctx context.Context, arg UpdateCartParams) (*Cart, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (*Course, error)
	UpdateOrderCourse(ctx context.Context, arg UpdateOrderCourseParams) (*OrderCourse, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
