// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateCart(ctx context.Context, arg CreateCartParams) (*Cart, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (*Course, error)
	CreateOrderCourse(ctx context.Context, arg CreateOrderCourseParams) (*OrderCourse, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteCart(ctx context.Context, cartID int32) error
	DeleteCourse(ctx context.Context, coursID int32) error
	DeleteOrderCourse(ctx context.Context, uscoID int32) error
	DeleteToken(ctx context.Context, userToken *string) error
	FindUserByPhone(ctx context.Context, userPhone *string) (*FindUserByPhoneRow, error)
	FindUserByUserPassword(ctx context.Context, arg FindUserByUserPasswordParams) (*FindUserByUserPasswordRow, error)
	FindUserByUsername(ctx context.Context, userName *string) (*FindUserByUsernameRow, error)
	GetAllCarts(ctx context.Context) ([]*Cart, error)
	GetAllCourses(ctx context.Context) ([]*Course, error)
	GetAllOrderCourses(ctx context.Context) ([]*OrderCourse, error)
	GetCartByID(ctx context.Context, cartID int32) (*Cart, error)
	GetCourseByID(ctx context.Context, coursID int32) (*Course, error)
	GetOrderCourseByID(ctx context.Context, uscoID int32) (*OrderCourse, error)
	UpdateCart(ctx context.Context, arg UpdateCartParams) (*Cart, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (*Course, error)
	UpdateOrderCourse(ctx context.Context, arg UpdateOrderCourseParams) (*OrderCourse, error)
	UpdateToken(ctx context.Context, arg UpdateTokenParams) (*User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (*User, error)
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (*User, error)
}

var _ Querier = (*Queries)(nil)

